export const ADD_USER = 'ADD_USER'
export const ADD_SCHEDULE = 'ADD_SCHEDULE'
export const RESET = 'RESET'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const EDIT = 'EDIT'
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'